from __future__ import annotations
import egglog


class Wire(egglog.Expr):
    @classmethod
    def from_input(cls, name: egglog.StringLike) -> Wire:...

    @classmethod
    def from_dff(cls, d: Wire) -> Wire: ...

    def __and__(self, other: Wire) -> Wire: ...

    def __or__(self, other: Wire) -> Wire: ...

    def __xor__(self, other: Wire) -> Wire: ...

    def __invert__(self) -> Wire: ...

    @classmethod
    def mux(cls, a: Wire, b: Wire, s: Wire) -> Wire: ...


class WireVec(egglog.Expr):
    @classmethod
    def add(cls, a: egglog.Vec[Wire], b: egglog.Vec[Wire]) -> WireVec: ...

    @classmethod
    def sub(cls, a: egglog.Vec[Wire], b: egglog.Vec[Wire]) -> WireVec: ...

    @classmethod
    def mul(cls, a: egglog.Vec[Wire], b: egglog.Vec[Wire]) -> WireVec: ...

    def __getitem__(self, index: egglog.i64Like) -> Wire: ...

    # def length(self) -> egglog.i64: ...
