"""Type definitions for emap module."""

from typing import Protocol


class NetlistDBProtocol(Protocol):
    """Protocol for NetlistDB interface used by rewrite functions"""
    def execute(self, query: str, params=None): ...
    def executemany(self, query: str, params_list): ...
    def commit(self): ...
    @property
    def auto_id(self) -> int: ...
    def _add_wirevec(self, wv: list[int]) -> int: ...
    def _create_or_lookup_wirevec(self, wv: list[int]) -> int: ...